---
title: 'Publication-N.A.C'
---
&nbsp;


### **Publication**  <font size="3">($*$ marks equal contribution) </font>   

1. **Zhang, X.**, Liu, J. and Zhu, Z., 2022. **Learning Coefficient Heterogeneity over Networks: A Distributed Spanning-Tree-Based Fused-Lasso Regression**. Journal of the American Statistical Association, pp.1-13. [[Link](https://arxiv.org/pdf/1905.11549.pdf)][[Supplementary](files/Supp_MSTClustering_FLASSO_ADMM.pdf)]   

1. Yang, H., **Zhang, X.**, Khanduri, P. and Liu, J., 2022, June. **Anarchic federated learning**. In International Conference on Machine Learning (pp. 25331-25363). PMLR. [[link](https://arxiv.org/pdf/2108.09875.pdf)]   

1. **Zhang, X.**, Fang, M., Liu, Z., Yang, H., Liu, J. and Zhu, Z., 2022, October. **Net-fleet: Achieving linear convergence speedup for fully decentralized federated learning with heterogeneous data**. In Proceedings of the Twenty-Third International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (pp. 71-80).   
      
1. Liu, Z., **Zhang, X.** and Liu, J., 2022, October. **Synthesis: A semi-asynchronous path-integrated stochastic gradient method for distributed learning in computing clusters**. In Proceedings of the Twenty-Third International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (pp. 151-160).    

1. Liu, Z., **Zhang, X.**, Khanduri, P., Lu, S. and Liu, J., 2022, October. **INTERACT: achieving low sample and communication complexities in decentralized bilevel learning over networks**. In Proceedings of the Twenty-Third International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (pp. 61-70).   

1. Liu, W., Mao, X. and **Zhang, X.**, 2022. **Fast and Robust Sparsity Learning Over Networks: A Decentralized Surrogate Median Regression Approach**. IEEE Transactions on Signal Processing, 70, pp.797-809.[[link](https://ieeexplore.ieee.org/document/9695243)]  

1. **Zhang, X.**, Liu, Z., Liu, J., Zhu, Z. and Lu, S., 2021. **Taming Communication and Sample Complexities in Decentralized Policy Evaluation for Cooperative Multi-Agent Reinforcement Learning**. Advances in Neural Information Processing Systems, 34, pp.18825-18838.
[[link](https://proceedings.neurips.cc/paper/2021/hash/9c51a13764ca629f439f6accbb4ec413-Abstract.html)]   

1. **Zhang, X.**, Liu, J., Zhu, Z. and Bentley, E.S., 2021, July. **Gt-storm: Taming sample, communication, and memory complexities in decentralized non-convex learning**. In Proceedings of the Twenty-second International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (pp. 271-280). [[Link](https://arxiv.org/pdf/2105.01231.pdf)]      

2. **Zhang, X.**, Liu, J., Zhu, Z. and Bentley, E.S., 2021, May. **Low Sample and Communication Complexities in Decentralized Learning: A Triple Hybrid Approach**. In IEEE INFOCOM 2021-IEEE Conference on Computer Communications (pp. 1-10). IEEE. [[Link](https://par.nsf.gov/servlets/purl/10283901)]    

4. **Zhang, X.**, Liu, J. and Zhu, Z., 2020, December. **Taming convergence for asynchronous stochastic gradient descent with unbounded delay in non-convex learning**. In 2020 59th IEEE Conference on Decision and Control (CDC) (pp. 3580-3585). IEEE. [[Link](https://arxiv.org/pdf/1805.09470.pdf)]  

11. Yang, H., **Zhang, X.**, Fang, M. and Liu, J., 2020, May. **Adaptive multi-hierarchical signSGD for communication-efficient distributed optimization**. In 2020 IEEE 21st International Workshop on Signal Processing Advances in Wireless Communications (SPAWC) (pp. 1-5). IEEE.
[[Link](https://ieeexplore.ieee.org/document/9154256)]     

6. **Zhang, X.**, Fang, M., Liu, J. and Zhu, Z., 2020, October. **Private and communication-efficient edge learning: a sparse differential gaussian-masking distributed SGD approach**. In Proceedings of the Twenty-First International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (pp. 261-270).
Vancouver	
 [[Link](https://arxiv.org/pdf/2001.03836.pdf)]  

7. Yang, H., **Zhang, X.**, Fang, M. and Liu, J., 2019, December. **Byzantine-resilient stochastic gradient descent for distributed learning: A lipschitz-inspired coordinate-wise median approach**. In 2019 IEEE 58th Conference on Decision and Control (CDC) (pp. 5832-5837). IEEE. [[Link](https://arxiv.org/pdf/1912.03208.pdf)]  

8. Haibo Yang, **Xin Zhang**, Minghong Fang, and Jia Liu. "**Byzantine-resilient stochastic gradient descent for distributed learning: A lipschitz-inspired coordinate-wise median approach.**" in Proc. IEEE CDC, Nice, France, Dec. 2019. [[Link](https://arxiv.org/pdf/1909.04532.pdf)]   

9. **Zhang, X.**, Liu, J., Zhu, Z. and Bentley, E.S., 2019, April. **Compressed distributed gradient descent: Communication-efficient consensus over networks**. In IEEE INFOCOM 2019-IEEE Conference on Computer Communications (pp. 2431-2439). IEEE.[[Link](https://arxiv.org/pdf/1812.04048.pdf)]  

10. **Zhang, X.**, Li, L., Ng, M.K. and Zhang, S., 2017. **Drug–target interaction prediction by integrating multiview network data**. Computational biology and chemistry, 69, pp.185-193.  

11. **Zhang, X.**, Weiguo, G. and Yun, S.U., 2015. **Electricity consumer archetypes study based on functional data analysis and K-means algorithm**. Power system technology, 39(2), pp.3153-3162.   

### **Preprint & In Preparation**  

**Spatial Heterogeneous Additive Partial Linear Model: A Joint Approach of Bivariate Spline and Forest Lasso** [[Available on Request]()]   
--Xin Zhang, Shan Yu, Xin Wang and Zhengyuan Zhu       


### **Master Creative Componenet**  
**Spatial CUSUM for Signal Region Detection** [[Link](https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=1049&context=creativecomponents)]    



